# KMOOC+ 온오프라인 세미나 자료

해당 내용은 1주차~7주차까지의 내용으로 구성되어 있습니다. 해당 파일에 대한 저작권은 박준혁(walter1023@daum.net)과 이경준(kjune18@naver.com)에게 있습니다.

# 1주차

- 기계학습 소개
- 기계학습 개발환경
- 행렬

## 기계학습 소개

### 기계학습의 개념

전통적으로 프로그램은 정해진 규칙에 따라 동작하여 프로그래머가 상황에 맞게 모든 상황에 대해 프로그램을 작성하여 컴퓨터가 무엇을 해야할지 명확히 정해주어야 하는 반면에,
기계학습은 스스로 학습 가능하여 스스로가 규칙을 찾도록 할 수 있습니다.

### 기계학습의 정의

아더 사무엘은 기계학습은 컴퓨터가 배울 수 있는 능력, 즉 프로그램으로 정의하지 않아도, 컴퓨터가 스스로 학습하여 실행할 수 있는 능력에 대한 연구분야라고 정의했습니다.

### 기계학습의 종류

기계학습에는 지도학습, 비지도학습, 그리고 강화학습이 있습니다.   
지도학습은 주어진 학습자료마다 명시적인 해답이 존재하여 모델이 예측한 값과 해답을 비교하며 모델을 학습시켜 나가는 방법입니다.   
비지도학습은 해답을 제시하지 않고 패턴을 분석하도록 학습하는 방법입니다. 대표적으로 분류하는 문제에 사용됩니다.   
강화학습은 주어진 환경에서 어떤 행동을 할때 얻는 보상을 극대화함으로 학습하는 방법입니다.

## 기계학습 개발환경

기계학습을 개발하는 환경은 다양하지만, 우리가 사용할 프로그래밍 언어는 파이썬입니다. 또한, 기계학습을 동작하기 위해 설치해야할 개발환경이 존재하는데, 주피터 노브북(랩)과 아나콘다가 있습니다.

### 쉘 명령어

주피터 노트북(랩)에서 쉘을 실행하는 명령어는 ctrl + enter 입니다.
쉘을 실행하고 다음 줄로 넘어가고 싶다면 shift + enter를 입력하면 됩니다.

### 마크다운

***진하게+기울임***

title level 1는 `#`을 1개 사용합니다.
title level 2는 `#`을 2개 사용합니다.

Italic체를 사용하고 싶으면 앞뒤에 `_` 혹은 `*`을 사용하면 됩니다.

blod는 `_`를 2개 사용하면 됩니다.

넘버링을 순서대로 하고 싶다면 `1.`을 연속해서 사용해도 됩니다.

bold와 Italic체를 함께 쓰고 싶다면 앞뒤에 `*`을 3번 사용하면 됩니다.

## 행렬

### 행렬의 덧셈
```
a = [[0, 1],
    [1, 2]]
    
b = [[3, 4],
    [4, 5]]
    
a + b  = [[3, 5],
          [5, 7]]

```

```
c = [[0],
    [1]]
    
d = [[2, 3]]

c + d = [[2, 3],
         [3, 4]]
```

### 행렬의 곱셈

```
a = [[0, 1],
    [2, 3]]

b = [[0],
     [1]]

numpy.dot(a, b) = [[1],
                   [3]]
```

# 2주차
- 함수와 뉴론
- 넘파이 튜토리얼

## 함수와 뉴론
__함수: $$y = f(x)$$__

기계학습이나 딥러닝이 나오기 전까지는 과학자들이 다양한 경우의 수를 생각해서 이를 만족하는 함수를 작성해야 했습니다.
그러나, 기계학습이 도입된 이후로는 모델이 이러한 함수를 직접 찾도록 하였습니다.

따라서 기계학습의 정의는 만능 함수 제조기 혹은 꿈의 함수 제조기라고 부를 수 있습니다.


__인공뉴론과 인공신경망__ : 인간의 생물학적 뉴론과 신경망을 기준으로 삼아 만든 모델링 기법

- 각각의 인공 뉴론은 노드(node)라고 부릅니다.   
- 뉴론을 여러 계층(layer)에 적재시킵니다.   
- 계층이 많아질수록 신경망은 점점 깊고 복잡해집니다.   
- 각 노드는 직전 계층과 직후 계층에 존재하는 다른 모든 노드와 연결되어 있습니다.

<center><img src="https://camo.githubusercontent.com/715d814c8857c8bb63cdbad5e58b9c355c0eb2329b6240fef240108261610b20/68747470733a2f2f6769746875622e636f6d2f69646562746f722f4b4d4f4f432d4d4c2f626c6f622f6d61737465722f6970796e622f696d616765732f6368322f4d4e4953542d4e4e312e504e473f7261773d74727565"></center>
<center><title>인공 신경망 예시</title></center>

## 넘파이 튜토리얼

넘파이(numpy)는 기계학습를 구현하는데 상당히 유용한 특징을 갖고 있습니다.
넘파이는 `import numpy`를 통해 import하여 사용가능합니다. 보통 이를 더 줄여서 `import numpy as np`로 하여 np로 numpy를 불러오도록 많이 사용합니다.

1. 강력한 N 차원 배열 객체
1. 정교한 브로드케스팅(Broadcast) 기능
1. 다양한 선형 대수학 함수와 난수 기능
1. 범용적 데이터 처리에 사용 가능한 다차원 컨테이너
1. C/C ++ 및 Fortran 코드 통합 도구

### 1차원 배열 만들기

numpy를 사용하여 1부터 10까지 원소로 구성된 1차원 배열을 만들어보세요.

In [2]:
import numpy as np

np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2차원 배열 만들기

numpy를 사용하여 1부터 10까지의 원소로 구성된 (2, 5)의 형상의 2차원 배열을 만들어보세요.

In [4]:
np.arange(1, 11).reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### 3차원 배열 만들기
numpy를 사용하여 1부터 12까지의 원소로 구성된 (2, 3, 2)의 형상의 3차원 배열을 만들어보세요.

In [29]:
np.arange(1, 13).reshape(2, 3, 2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

위의 3차원 배열에서 맨 앞의 차원을 줄여서 2차원 배열로 다시 만들어보세요.

In [33]:
a = np.arange(1, 13).reshape(2, 3, 2)
a.reshape(-1, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

### 슬라이싱

슬라이싱은 [a:b:c]로 되어있습니다.
a는 시작 인덱스(해당 인덱스 포함), b는 마침 인덱스(해당 인덱스 미포함), c는 step으로서 몇개씩 끊어서 가져올지와 방향을 정하는 것을 의미합니다.

In [5]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
numbers[:5]

[1, 2, 3, 4, 5]

In [8]:
numbers[::2]

[1, 3, 5, 7, 9]

In [39]:
numbers[-1:]

[10]

In [45]:
numbers[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

# 3주차
- 인공뉴론의 동작원리
- 미분
- 활성화 함수

## 인공뉴론의 동작원리
가중치와 편향
가중치는 각 입력 신호가 결과에 미치는 중요도를 조절하는 매개변수이고, 편향은 뉴론의 활성화 조건을 설정하는 매개변수 입니다.

$$ y = ax + b $$

예를들어, 해당 식에서 가중치는 a이고, 편향은 b입니다.

다음은 가중치를 이용하여 OR게이트를 구현해본 것입니다.
여기서 w의 값은 주어졌지만, 기계학습을 진행하면 해당 w값이 최적화 될 것입니다.

In [46]:
import numpy as np
def OR(x1, x2):
    x = np.array([1, x1, x2])         # input
    w = np.array([-0.3, 0.5, 0.5])    # bias + weight
    return np.dot(x, w) > 0

In [47]:
print("OR(False, False) = ", OR(False, False))
print("OR(False, True) = ", OR(False, True))
print("OR(True, False) = ", OR(True, False))
print("OR(True, True) = ", OR(True, True))

OR(False, False) =  False
OR(False, True) =  True
OR(True, False) =  True
OR(True, True) =  True


## 미분

평균변화율 = $$ \frac{f(x_2)-f(x_1)}{x_2 - x_1}$$

합성함수의 미분법

$$ y = f(g(x)) $$
$$ f(g(x))' = {f'(g(x))}{g'(x)}$$

삼각함수의 미분법
$$f(x) = sin(x), f'(x) = cos(x)$$
$$f(x) = cos(x), f'(x) = -sin(x)$$
$$f(x) = tan(x), f'(x) = sec^2(x)$$
$$f(x) = sec(x), f'(x) = sec(x)tan(x)$$
$$f(x) = csc(x), f'(x) = -csc(x)cot(x)$$
$$f(x) = cot(x), f'(x) = -csc^2(x)$$

## 활성화 함수
활성화 함수는 $y = ax + b$에서 출력된 y값을 다시 입력으로 하여 뉴론을 활성화 할지 말지를 결정해주는 함수입니다.

### 종류
1. 시그모이드(Sigmoid)
2. 렐루(Relu)
3. 스탭(Step)
4. 쌍곡탄젠트(tanh)
5. 소프트맥스(softmax) - 주로 출력층에서 사용

<center> <img src ="https://blog.kakaocdn.net/dn/bb0loO/btrgdF1UM76/yARoWX7j4TqvImCSBNVkB1/img.png"></center>
<center>활성화 함수</center>

# 4주차
- 퍼셉트론
- 퍼셉트론 알고리즘
- 퍼셉트론 코딩

## 퍼셉트론

퍼셉트론은 인공신경망의 한 종류로 인식되며 1957년에 프랑크 로젠블라트가 고안한 알고리즘입니다.

퍼셉트론은 다수의 입력을 받아 하나의 출력을 내보냅니다. 즉, 퍼셉트론은 선형모델입니다.
<center><img src="https://camo.githubusercontent.com/8f32abbc5cd3fb0182b0437b3099753d72e9f3c3a85032aeef38cc69fad72b2d/68747470733a2f2f6769746875622e636f6d2f69646562746f722f4b4d4f4f432d4d4c2f626c6f622f6d61737465722f6970796e622f696d616765732f6368332f73696d706c655f6e6f64655f61637469766174652e504e473f7261773d74727565"></center>

### 퍼셉트론 학습과정

1. 학습 자료 입력
1. w와 b를 이용하여 z계산
1. 활성화 함수를 이용하여 y_hat계산
1. y_hat과 y값 비교하여 새로운 가중치 값 생성
1. 새로운 가중치를 이용하여 z계산

### 퍼셉트론 한계

퍼셉트론은 선형모델이기 때문에 비선형 문제에서는 적합하지 않다. 대표적인 예로는 XOR신경망이 있다.

퍼셉트론 구현

In [13]:
import numpy as np

x = np.array([[1.0, 1.0], [2.0, -2.0], [-1.0,-1.5], [-2.0, -1.0], [-2.0,1.0], [1.5, -0.5]]) 
print("x_len:", len(x))
X = np.c_[ np.ones(len(x)), x ]         # trainining samples, concatenate
y = np.array([1, -1, -1, -1, 1, 1])      # class labels
w = np.array([0, 1.0, 0.5])              # initial weight
maxy, miny = y.max(), y.min()

epochs = 2
eta = 0.2
for _ in np.arange(epochs): 
    for xi, yi in zip(X, y):
        z = np.dot(xi, w)                              # Compute net input, same as np.dot(w.T, x)
        yhat = np.where(z > 0.0, maxy, miny)           # Apply step func and get output, z가 0보다 크면 maxy, 그렇지 않으면 miny의 위치 값으로 설정
        delta = eta * (yi - yhat) * xi                 # Compute delta    
        w += delta                                     # Adjust weight
#         print('x{}, \t (y,yhat)=({},{}), \tdelta{}, \tw{}'.format(xi, yi, yhat, delta, np.round(w,2)))
print('w = ', w)

x_len: 6
w =  [0.8 0.6 1.3]


# 참조

[활성화함수](https://www.google.com/url?sa=i&url=https%3A%2F%2Fheeya-stupidbutstudying.tistory.com%2F38&psig=AOvVaw2tykJOWs8K9jWw2eSTNSqP&ust=1650019509543000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCMCTnPKvk_cCFQAAAAAdAAAAABAD)