# Week 9-2 XOR Neural Network Modeling
#### Machine Learning with Python by idebtor@gmail.com

-----------------------------------

## 1. 입력과 출력: XOR 데이터

In [1]:
import numpy as np
X = np.array([[0, 0, 1, 1], [0, 1, 0, 1]])
y = np.array([[0, 1, 1, 0]])
print('X.shape={}. y.shape{}'.format(X.shape, y.shape))
print(X)
print(y)

X.shape=(2, 4). y.shape(1, 4)
[[0 0 1 1]
 [0 1 0 1]]
[[0 1 1 0]]


## 3. 가중치: 행렬의 형상 구현

In [3]:
import numpy as np
n_x = X.shape[0]
n_y = y.shape[0]
n_h = 3
np.random.seed(1)
W1 = 2 * np.random.random((n_h, n_x)) - 1
W2 = 2 * np.random.random((n_y, n_h)) - 1
print("W1: {}".format(W1))
print("W2: {}".format(W2))

W1: [[-0.16595599  0.44064899]
 [-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]]
W2: [[-0.62747958 -0.30887855 -0.20646505]]


## 5. XOR 객체 구현

In [4]:
class NeuralNetwork():
    """This class implements a multi-perceptron
       with backpropagation. This handles a simple logic
       such as OR, AND, NAND, and NOR gates, including XOR."""
    
    def __init__(self, net_arch, eta = 0.1, epochs = 10000, random_seed = 1):
        self.layers = len(net_arch)
        self.net_arch = net_arch
        self.eta  = eta
        self.epochs = epochs
        self.random_seed = random_seed
        
    def g(self, x):
        return 1 / (1 + np.exp((-x)))
    
    def g_prime(self, x):
        return self.g(x) * (1 - self.g(x))